modLoader="javafml"
loaderVersion="[28,)"

[[mods]]

modId="anvildata"
version="${file.jarVersion}"
displayName="Anvil Data"
authors="Eutros"
description='''
A small mod that exposes anvil crafting to datapacks.
'''
